development:
  adapter: postgresql
  encoding: unicode
  database: joshuarieken-site_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: joshuarieken-site_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: joshuarieken-site_production
  pool: 5
